//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiagramDesigner.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DiagramDesigner.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aligment.
        /// </summary>
        public static string Aligment {
            get {
                return ResourceManager.GetString("Aligment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrange.
        /// </summary>
        public static string Arrange {
            get {
                return ResourceManager.GetString("Arrange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backward.
        /// </summary>
        public static string Backward {
            get {
                return ResourceManager.GetString("Backward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bring Forward.
        /// </summary>
        public static string BringForward {
            get {
                return ResourceManager.GetString("BringForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bring To Front.
        /// </summary>
        public static string BringToFront {
            get {
                return ResourceManager.GetString("BringToFront", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        public static string Cut {
            get {
                return ResourceManager.GetString("Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagram.
        /// </summary>
        public static string Diagram {
            get {
                return ResourceManager.GetString("Diagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagram Designer.
        /// </summary>
        public static string DiagramDesigner {
            get {
                return ResourceManager.GetString("DiagramDesigner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flow Chart.
        /// </summary>
        public static string FlowChart {
            get {
                return ResourceManager.GetString("FlowChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forward.
        /// </summary>
        public static string Forward {
            get {
                return ResourceManager.GetString("Forward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        public static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grouping.
        /// </summary>
        public static string Grouping {
            get {
                return ResourceManager.GetString("Grouping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal.
        /// </summary>
        public static string Horizontal {
            get {
                return ResourceManager.GetString("Horizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New diagram.
        /// </summary>
        public static string NewDiagram {
            get {
                return ResourceManager.GetString("NewDiagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        public static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        public static string Paste {
            get {
                return ResourceManager.GetString("Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        public static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The diagram is not empty. Do you want to save changes before closing a diagram?.
        /// </summary>
        public static string SaveAfterCloseMessage {
            get {
                return ResourceManager.GetString("SaveAfterCloseMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes?.
        /// </summary>
        public static string SaveAfterCloseTitle {
            get {
                return ResourceManager.GetString("SaveAfterCloseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        public static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Backward.
        /// </summary>
        public static string SendBackward {
            get {
                return ResourceManager.GetString("SendBackward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send To Back.
        /// </summary>
        public static string SendToBack {
            get {
                return ResourceManager.GetString("SendToBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shapes.
        /// </summary>
        public static string Shapes {
            get {
                return ResourceManager.GetString("Shapes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Back.
        /// </summary>
        public static string ToBack {
            get {
                return ResourceManager.GetString("ToBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Front.
        /// </summary>
        public static string ToFront {
            get {
                return ResourceManager.GetString("ToFront", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ungroup.
        /// </summary>
        public static string Ungroup {
            get {
                return ResourceManager.GetString("Ungroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical.
        /// </summary>
        public static string Vertical {
            get {
                return ResourceManager.GetString("Vertical", resourceCulture);
            }
        }
    }
}
